apiVersion: v1
kind: Service
metadata:
  labels:
    app: ftps
  name: ftps
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  ports:
  - name: data
    port: 20
    targetPort: 20
  - name: ftps
    port: 21
    protocol: TCP
    targetPort: 21
  - name: ftps-pasv-first
    port: 50000
    protocol: TCP
    targetPort: 50000
  - name: ftps-pasv-second
    port: 50001
    protocol: TCP
    targetPort: 50001
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.10.12


---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ftps
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps_image
        imagePullPolicy: Never
        name: ftps
        ports:
        - containerPort: 21
        - containerPort: 50000
        - containerPort: 50001
