apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
#  strategy:
#    rollingUpdate:
#      maxSurge: 25%
#      maxUnavailable: 25%
#    type: RollingUpdate
  template:
    metadata:
#      creationTimestamp: null
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps_image
        imagePullPolicy: Never
        name: ftps
        ports:
        - containerPort: 21
        - containerPort: 50000
        - containerPort: 50001