apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  ports:
  - name: data
    protocol: TCP
    port: 20
    targetPort: 20
  - name: ftps
    protocol: TCP
    port: 21
    targetPort: 21
  - name: ftps-pasv-first
    protocol: TCP
    port: 50000
    targetPort: 50000
  - name: ftps-pasv-second
    protocol: TCP
    port: 50001
    targetPort: 50001
  type: LoadBalancer
  loadBalancerIP: 192.168.10.12