apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
spec:
  selector:
    app: influxdb
  ports:
  - name: incluxdb
    protocol: TCP
    port: 8086
    targetPort: 8086