apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    component: nginx
spec:
  containers:
  - name: nginx
    image: nginx_image
    imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector: 
    component: nginx
  ports:
  - protocol: http
    port: 80
    targetPort: 80
  - protocol: https
    port: 433
    targetPort: 433
  - protocol: ssh
    port: 22
    targetPort: 22
  type: LoadBalancer