apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
spec:
  selector: 
    app: nginx
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer
  loadBalancerIP: 192.168.10.10