apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
spec:
  selector:
    app: phpmyadmin
  ports:
  - name: phpmyadmin
    protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer
  loadBalancerIP: 192.168.10.10