apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  ports:
  - name: wordpress
    protocol: TCP
    port: 5050
    targetPort: 5050
  type: LoadBalancer
  loadBalancerIP: 192.168.10.11