apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress_image
        name: wordpress
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5050

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector: 
    app: wordpress
  ports:
  - name: wordpress
    port: 5050
    targetPort: 5050
  type: LoadBalancer
  loadBalancerIP: 192.168.10.11